-- MySQL Script generated by MySQL Workbench
-- Fri May  4 17:33:27 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema project_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema project_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `project_db`;
CREATE SCHEMA IF NOT EXISTS `project_db` DEFAULT CHARACTER SET utf8 ;
USE `project_db` ;

-- -----------------------------------------------------
-- Table `project_db`.`periodical`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_db`.`periodical` (
  `idperiodical` INT(11) NOT NULL AUTO_INCREMENT,
  `namePer` VARCHAR(100) NOT NULL,
  `pricePer` INT(11) NOT NULL,
  `short_description` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`idperiodical`),
  UNIQUE INDEX `namePer_UNIQUE` (`namePer` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project_db`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_db`.`article` (
  `idarticle` INT(11) NOT NULL AUTO_INCREMENT,
  `nameArt` VARCHAR(200) NOT NULL,
  `date` DATE NOT NULL,
  `idperiodical` INT(11) NOT NULL,
  `text` VARCHAR(20000) NOT NULL,
  PRIMARY KEY (`idarticle`, `idperiodical`),
  INDEX `fk_article_periodical_idx` (`idperiodical` ASC),
  CONSTRAINT `fk_article_periodical`
    FOREIGN KEY (`idperiodical`)
    REFERENCES `project_db`.`periodical` (`idperiodical`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_db`.`user` (
  `iduser` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role` ENUM('USER', 'ADMIN') NOT NULL DEFAULT 'USER',
  `money` INT(11) NOT NULL DEFAULT '0',
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project_db`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_db`.`payment` (
  `idpayment` INT(11) NOT NULL AUTO_INCREMENT,
  `pricePay` INT(11) NOT NULL,
  `iduser` INT(11) NOT NULL,
  PRIMARY KEY (`idpayment`),
  INDEX `fk_payment_user1_idx` (`iduser` ASC),
  CONSTRAINT `fk_payment_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `project_db`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project_db`.`periodical_has_payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_db`.`periodical_has_payment` (
  `idperiodical` INT(11) NOT NULL,
  `idpayment` INT(11) NOT NULL,
  PRIMARY KEY (`idperiodical`, `idpayment`),
  INDEX `fk_periodical_has_payment_payment1_idx` (`idpayment` ASC),
  INDEX `fk_periodical_has_payment_periodical1_idx` (`idperiodical` ASC),
  CONSTRAINT `fk_periodical_has_payment_payment1`
    FOREIGN KEY (`idpayment`)
    REFERENCES `project_db`.`payment` (`idpayment`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_periodical_has_payment_periodical1`
    FOREIGN KEY (`idperiodical`)
    REFERENCES `project_db`.`periodical` (`idperiodical`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `project_db`.`user_has_periodical`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_db`.`user_has_periodical` (
  `iduser` INT(11) NOT NULL,
  `idperiodical` INT(11) NOT NULL,
  PRIMARY KEY (`iduser`, `idperiodical`),
  INDEX `fk_user_has_periodical_periodical1_idx` (`idperiodical` ASC),
  INDEX `fk_user_has_periodical_user1_idx` (`iduser` ASC),
  CONSTRAINT `fk_user_has_periodical_periodical1`
    FOREIGN KEY (`idperiodical`)
    REFERENCES `project_db`.`periodical` (`idperiodical`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_has_periodical_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `project_db`.`user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `project_db`.`article`
(`nameArt`,`date`,`idperiodical`,`text`)
VALUES
('Second Article', '2018-02-02', '1', 'It\'s my second text'),
('Third Article', '2018-02-01', '2', 'It\'s my third text'),
('6 ознак того, що ви є емпатом', '2018-05-04', '9', '<p>Емпати надто чутливі до емоцій, настрою й енергії оточуючих. Це означає, що вони впадають в стрес через речі, які не хвилюють менш чутливих людей. Далі представлені шість ознак, які негативно позначаються на стані емпата. <p><p>1. Інконгруентна поведінка <p>2. Негатив <p>3. Агресивна поведінка <p>4. Страждання інших людей <p>5. Зайві переживання <p>6. Непорозуміння'),
('6 законів психології, знання яких може змінити ваше життя', '2018-05-04', '9', '<p>Представлені нижче шість психологічних феноменів допоможуть вам не тільки краще зрозуміти, чому люди щодня повторюють одні й ті само дурниці, але і самим стати краще, раціональніше.<p>Розуміння законів психології допоможе вам пояснити ірраціональність зовнішнього світу і ті дурниці, які люди здійснюють щодня.<p><p>Ефект Претфелла. Якщо ви недосконалі, люди будуть любити вас більше <p><p>Ефект Пігмаліона. Великі очікування збільшують продуктивність <p><p>Парадокс вибору. Чим більше у нас опцій на вибір, тим менше ми задоволені прийнятим рішенням <p><p>Ефект свідка. Чим більше людей навколо потребує допомоги, тим менше ймовірності, що вони її отримають <p><p>Ефект рампи. Люди, чия голова постійно забита роздумами, не помічають очевидних речей<p><p>Ефект фокусування. Люди переоцінюють значимість речей і явищ, про які розмірковують '),
('Топ жіночих звичок, які найбільше дратують чоловіків', '2018-05-04', '9', '<p>Образи з приводу і без <p>Тотальний контроль <p>Наведення краси по всім закуткам помешкання <p>Прибирання в його речах <p>Постійно питати про що чоловік думає, чи кохає він жінку <p>Жінки постійно страждають, що їм нічого одягти, але при цьому годинами одягаються <p>Постійно думати про дієти і головне, - увесь час питати, - чи не занадто вона розтовстіла <p>Чоловіків дратує, коли жінки комплексують <p>Чоловіків дратує, коли жінка поводиться так, ніби секс з ним - це велика послуга <p>\"Сексуальні трупи\" <p>Не потрібно озвучувати бажання натяками <p>Залучення третіх осіб в сімейні проблеми <p>Жінки часто тягають їжу з чоловічої тарілки <p>Багато говорить і з порога розповідає про свій день <p>Жінки часто вимагають розгорнуто оцінити їх зовнішній вигляд <p>Плаче без помітної причини'),
('15 речей, за які ми ніколи не повинні виправдовуватися і звітувати', '2018-05-04', '9', '<p>1. Ви не зобов`язані нікому пояснювати вашу життєву ситуацію <p>2. Ви не зобов`язані нікому пояснювати ваші життєві пріоритети <p>3. Ви не зобов`язані вибачатися, якщо вам не шкода <p>4. Ви не зобов`язані ні перед ким виправдовуватися за час, проведений на самоті <p>5. Ви не зобов`язані погоджуватися ні з чиїми особистими переконаннями <p>6. Ви не зобов`язані говорити «Так» <p>7. Ви не зобов`язані виправдовуватися за свою зовнішність <p>8. Ви не зобов`язані нікому пояснювати ваші уподобання в їжі <p>9. Ви не зобов`язані нікому звітувати про ваше сексуальне життя <p>10. Ви не зобов`язані нікому пояснювати ваш кар`єрний або особистий вибір <p>11. Ви не зобов`язані пояснювати ваші політичні чи релігійні погляди <p>12. Ви не зобов`язані пояснювати, чому самотні <p>13. Ви не зобов`язані ні з ким зустрічатися тільки тому, що вас попросили <p>14. Ви не зобов`язані нікому пояснювати своє рішення про шлюб <p>15. Ви не зобов`язані пояснювати ваш вибір у стосунках '),
('Три дієві засоби від безпорадності', '2018-05-04', '9', '<p>Засіб 1: Робіть що-небудь. <p>Засіб 2: Геть від безпорадності - маленькими кроками. <p>Засіб 3: Інший погляд.');

INSERT INTO `project_db`.`periodical`
(`namePer`,`pricePer`,`short_description`)
VALUES
('First Periodical', '10', 'It\'s my first periodical'),
('Second Periodical', '12', 'It\'s my second periodical'),
('Психологія', '24', 'Статті про те, як пізнати себе.'),
('ІТ', '13', 'Видання, де публікуються статті про новітні технології'),
('New Periodical', '0', 'This periodical was created like test'),
('VoGUE', '12', 'Magazine about fashion'),
('Money', '14', 'About business'),
('About smth', '7', 'Articles about everything\r\non the world');

INSERT INTO `project_db`.`user`
(`name`,`surname`,`login`,`password`,`role`,`money`,`phone`)
VALUES
('User', 'Hubenko', 'vlada@gmail.com', '13228bebea5f9ea8456ed4b8b1a2835e', 'USER', '198', ''),
('Admin', 'Hubenko', 'admin@ukr.net', 'f6fdffe48c908deb0f4c3bd36c032e72', 'ADMIN', '18', '');